### ISSUE TITLE
[BUG] [BOUNTY 0.25 XMR] DNS leak in version 2.0.0 when not using WARP or DNSCrypt or V2Ray / No HNS Support 

### ISSUE THREAD

**Issue by freQniK** [MathNodes/meile-gui#101]
Like many of the Android apps on Sentinel, the DNS requests are not routed through the tunnel unless HNS is specifically used. Currently, we do not have an option for Handshake in 2.0.0 and are using the system DNS (most likely Google). But, this is only for Wireguard as Meile for Linux currently routes the DNS traffic through the V2Ray tunnel. 

However, if the user turns on WARP first then DNS will be routed DoH through Cloudflare - a great improvement. We also have the framework for DNSCrypt with user selected resolvers. This will be completed soon. 

Nevertheless, I would like there to be a HNS selection and the code written to use HNS on the node side via client DNS requests.

**Comment by MathNodes** [comment]
This is moot. Wireguard tunnels DNS and uses DNS on node. There are settings in the connect() routine that do this by @Tkd-Alex
