### ISSUE TITLE
support more linux distro

### ISSUE THREAD

**Issue by Just-some-one** [MathNodes/meile-gui#24]
i guess if you create rpm package that would allow more linux distro like RHEL(and all it's derivative) fedora and suse

**Comment by MathNodes** [comment]
Crossed our mind. There will be a new release in a few days v1.0.4 with UI enhancements and a HUGE security implementation that is currently lacking in the Sentinel DVPN apps. We are excited for this release. We will make it our plan to bundle an RPM as well as the .deb and MacOS releases. Thanks for suggesting it. It is certainly welcomed when people suggest ideas to further our products.

**Comment by Just-some-one** [comment]
@MathNodes thanks for you and keep the good work :)

**Comment by MathNodes** [comment]
An RPM for Fedora 36 like systems has been created in our pre-release of version 1.1.0. 

https://github.com/MathNodes/meile-gui/releases/tag/v1.1.0

https://github.com/MathNodes/meile-gui/releases/download/v1.1.0/meile-gui-1.1.0-1.fc36.x86_64.rpm

I'll leave this issue open a little longer in case there are any further suggestions of linux builds
