### ISSUE TITLE
BUG: Real-time bandwidth doesn't parse subscriptions of 1GB ~ 999.00MB

### ISSUE THREAD

**Issue by MathNodes** [MathNodes/meile-gui#31]
I thought I fixed this in a commit. Essentially, it is parsing values with a `GB` string in the variable. This can be overcome by checking for `MB` when `GB` throws an exception as shown in the console.

**Comment by BrendenF86** [comment]
- https://github.com/MathNodes/meile-gui/labels/bug

**Comment by BrendenF86** [comment]
https://github.com/MathNodes/meile-gui/labels/bug

https://github.com/MathNodes/meile-gui/labels/enhancement

https://github.com/MathNodes/meile-gui/labels/help%20wanted

https://github.com/MathNodes/meile-gui/labels/question

https://github.com/MathNodes/meile-gui/labels/wontfix

https://github.com/MathNodes/meile-gui/labels/duplicate

https://github.com/MathNodes/meile-gui/labels/invalid

https://github.com/MathNodes/meile-gui/labels/good%20first%20issue

https://github.com/MathNodes/meile-gui/

**Comment by MathNodes** [comment]
https://github.com/MathNodes/meile-gui/commit/2190fc9c6bf80f8ec6f29f94dfdcb3046e82b162
