### ISSUE TITLE
Can not Warp

### ISSUE THREAD

**Issue by Alien901** [MathNodes/meile-gui#33]
using v1.4.3 on Windows11buid 22621.1413, getting warp error cant warp any nodes. kindly release new updated app with v2ray stuff.
![warp](https://user-images.githubusercontent.com/6206953/227986173-170ce376-2d17-48d8-b2c5-d1d5cf0ec37e.jpg)

**Comment by MathNodes** [comment]
Will look into this. Building the Windows v2ray this week. Should have a full release out next week. Will troubleshoot WARP in the v2ray release as well.

Thanks for creating an iussue.

**Comment by MathNodes** [comment]
Hi - didn't get a chance to review the WARP issue, but there is a beta version with v2ray support: https://github.com/MathNodes/meile-gui/releases/tag/v1.5.1-rc0-win

**Comment by MathNodes** [comment]
I'm looking to improve WARP on Windows and hoping to get some help with this. But we are weighing another alternative and that is to introduction dnscrypt-proxy instead. There was interest from another user of getting this implemented.

**Comment by freQniK** [comment]
Yes :) I'm using on my Mac right now!

<img width="1440" alt="Screen Shot 2023-08-21 at 7 54 44 PM" src="https://github.com/MathNodes/meile-gui/assets/93114223/77362488-4edd-4f5f-bd57-e271c6673dcc">

**Comment by freQniK** [comment]
https://github.com/MathNodes/meile-gui/commit/16e1eeb0fc6fc94b21915612b97440c6c259011f

**Comment by freQniK** [comment]
Syahpian reported the same problem in Windows still as the OP

**Comment by MathNodes** [comment]
deprecated with a more improved dnscrypt proxy with user selected resolvers. closing now.
