### ISSUE TITLE
Cannot install on Linux Mint 19.3

### ISSUE THREAD

**Issue by shmaiz** [MathNodes/meile-gui#37]
Hello.

I cannot install any (.deb) of the meile-gui software on my Linux Mint 19.3 machine.
It requires a dependency (openresolv) that is higher than I can install. (>= 3.10)

The highest version of openresov my system can have is (3.8.0-1).

Is where a work around for this? Thanks.

Added screenshots of the system and the installing error.
![Selection_655](https://user-images.githubusercontent.com/45763444/231304953-2c52cc59-4e03-46c4-ba93-b66ef4ac99b2.jpg)
![Selection_656](https://user-images.githubusercontent.com/45763444/231304983-785d6c17-1db7-4b8d-9022-9a06d040dbb0.jpg)

**Comment by MathNodes** [comment]
```
Linux Mint 19.3 is based on Ubuntu 18.04.3 LTS
```

I'm afraid I may have to create an Ubuntu 18.04 version for this to work for you. GLIBC libraries will be outdated in the binary I create for 20.04 and the binary will not run. I don't have plans on creating a binary for older Ubuntu versions, and I recommend you upgrade your Linux Mint to be compatible with Ubuntu 20.04 versions. If this is impossible, I will put it in the task list to spin up a Ubuntu 18.04 VM. But, don't get your hopes up anytime soon as there is a lot of ongoing development and older release candidates is not high priority.
