### ISSUE TITLE
Mac version doesn't work with Catalina

### ISSUE THREAD

**Issue by tomfrankel** [MathNodes/meile-gui#40]
I'd love to try this - I use Solar DVPN on my phone, but need a desktop solution for travel, but I get an error message saying I require macOS 11.0 or later. I've got 10.15.1 and on a Macbook Air that's a couple years old, it's nearly impossible to upgrade.

**Comment by freQniK** [comment]
This would be a PITA for us to build on, because I only have the two Airs (Intel & Apple Silicon).

I'll put a bounty on this for someone to eventually come along and build it on older OS X versions with our assistance

**Comment by freQniK** [comment]
deprecated version. Won't build.
