### ISSUE TITLE
[0.15 XMR BOUNTY] Build Meile dVPN on Catalina OS X

### ISSUE THREAD

**Issue by freQniK** [MathNodes/meile-gui#42]
To broaden the range of available devices Meile dVPN can run on we are announcing this bounty to build Meile GUI on Catalina. You will receive our assistance in the process of building a binary application for this release version of OS X. 

It is pretty straight forward and requires Python 3.10, Pyinstaller 5.10 and several python packages that can be installed via pip. The final build process is simply to run `bash pyinstaller2.cmd`. We will guid you through the process for this bounty. 

We don't have a apple laptop with Catalina so this is the reason for the bounty.

**Comment by freQniK** [comment]
#40

**Comment by Ritikkhulbe** [comment]
Hey, if this task is still needed to be done, please let me know,  I'm new to git/github and i do have a macbook

**Comment by VividhPandey003** [comment]
Hey, I wanted to know what are the requirements for this issue to be solved.

**Comment by freQniK** [comment]
Hey, I'll respond with details in the coming days. Currently working on an API. Can expect a response by Friday.

**Comment by VividhPandey003** [comment]
> Hey, I'll respond with details in the coming days. Currently working on an API. Can expect a response by Friday.

sure, thanks for replying

**Comment by freQniK** [comment]
So, since there are two users here interested in compiling Meile-gui. Do either of you run Catalina, OS X v10.15 @VividhPandey003 @Ritikkhulbe ?

This is not high priority, but I can outline steps to building Meile-gui on this deprecated OS X version if either of you are willing to attack the issue.

**Comment by freQniK** [comment]
I've decided this is deprecated and no longer needed. Closing.
