### ISSUE TITLE
[0.5 XMR BOUNTY] Build a Binary Package Release for Arch Linux

### ISSUE THREAD

**Issue by freQniK** [MathNodes/meile-gui#45]
There has been about a half dozen or so requests to build a binary package for Arch Linux. 

We use Pyinstaller to build the binary releases and typically, once all your dependencies are installed it is as simple as running:

`bash pyinstaller2.cmd`

I never worked with Arch linux so I don't know how to build a package for it. That would be up to you. We will start without the FIAT gateway for now until we can build trust and I can hand over the proper scrtsxx.py file with the API keys. 

Assistance is available for the pyinstaller part, but the Arch package is solely at your responsibility. 

https://github.com/MathNodes/meile-gui/issues/41

**Comment by Tkd-Alex** [comment]
HI :)
About this i was able to cretae a binary package (without the Linux dependeces , wireguard, resolvconf etc)
The main problem It's that we have some connection issue (i think is about dns), because I'm able to ping

**Comment by Tkd-Alex** [comment]
`Failed to start: main/commands: failed to load config: [/home/tkd-alex/.sentinelcli/v2ray_config.json] > fail to load /home/tkd-alex/.sentinelcli/v2ray_config.json: open /home/tkd-alex/.sentinelcli/v2ray_config.json: no such file or director`

![image](https://github.com/MathNodes/meile-gui/assets/14061593/5b2bad0d-58e9-497b-ac97-9139aec87715)

As you can see I'm unable to ping mio-ip.it.

![20230805-114321](https://github.com/MathNodes/meile-gui/assets/14061593/aa1e1009-0b44-4646-988b-c5dcf1197b02)

**Comment by freQniK** [comment]
I think the issue here is v2ray is failing to load. We may have to build v2ray on the arch architecture. See if you can get the prebuilt v2ray command to run with `v2ray help` and see if it doesn't spit out some library error

**Comment by Tkd-Alex** [comment]
> I think the issue here is v2ray is failing to load. We may have to build v2ray on the arch architecture. See if you can get the prebuilt v2ray command to run with `v2ray help` and see if it doesn't spit out some library error

No error on v2ray. Btw, It's strange, I've tried only wireguard nodes... 
The issue today doesn't exist on DNS side, today all working :confounded:

**Comment by MathNodes** [comment]
Question, does Arch linux have `pkexec`? The graphical sudo command essentially?

**Comment by MathNodes** [comment]
Upping the Bounty by **0.075**

**Comment by Tkd-Alex** [comment]
> Question, does Arch linux have `pkexec`? The graphical sudo command essentially?

Sure...
Meile is working very well on my ArchLinux instance :) 

I've built a version with pyinstaller, shared with a friend but we have some issue on connection/DNS side

**Comment by freQniK** [comment]
I'm doubling this bounty. I think we should try to build from the main branch. Please wait for a commit coming through shortly that will update that branch for the build. I'll post a comment here with the commit when ready.

**Comment by Tkd-Alex** [comment]
In the meantime I'm back at my family home, tested the build on another PC with Arch and all work. I think the best solution is to spin a Manjaro VM and check what's the connection issue founded by Trinity

**Comment by freQniK** [comment]
Is this working after the network upgrade? If so, can you send me the AUR package. I have a user via e-mail who would like to try it. If you could send it on Telegram that would be fine. O/w I can create you a Nextcloud account on my instance.

**Comment by Tkd-Alex** [comment]
> Is this working after the network upgrade? If so, can you send me the AUR package. I have a user via e-mail who would like to try it. If you could send it on Telegram that would be fine. O/w I can create you a Nextcloud account on my instance.

oh well, after the nework upgrade I don't have test it :rofl: 

> I'm doubling this bounty. I think we should try to build from the main branch. Please wait for a commit coming through shortly that will update that branch for the build. I'll post a comment here with the commit when ready.

Let's do this... I'll create the AUR package directly on main-branch.
Don't forget to add the update requirements.txt file and update the pyinstaller command :smile:

**Comment by freQniK** [comment]
> > Is this working after the network upgrade? If so, can you send me the AUR package. I have a user via e-mail who would like to try it. If you could send it on Telegram that would be fine. O/w I can create you a Nextcloud account on my instance.
> 
> oh well, after the nework upgrade I don't have test it 🤣
> 
> > I'm doubling this bounty. I think we should try to build from the main branch. Please wait for a commit coming through shortly that will update that branch for the build. I'll post a comment here with the commit when ready.
> 
> Let's do this... I'll create the AUR package directly on main-branch. Don't forget to add the update requirements.txt file and update the pyinstaller command 😄

Okay. I'll add this tomorrow. Playing around for the rest of the night :)

**Comment by freQniK** [comment]
https://github.com/MathNodes/meile-gui/releases/download/v1.7.7/meile-gui-1.7.7-1-x86_64.pkg.tar.zst
