### ISSUE TITLE
coinstats deprecated API

### ISSUE THREAD

**Issue by Tkd-Alex** [MathNodes/meile-gui#58]
Hi! We could have some issue regarding the GetPriceAPI class.
- https://api.coinstats.app/public/v1/tickers?exchange=KuCoin&pair=dvpn-USDT
- https://api.coinstats.app/public/v1/tickers?exchange=KuCoin&pair=DVPN-USDT
- https://api.coinstats.app/public/v1/tickers?exchange=KuCoin&pair=atom-USDT
- https://api.coinstats.app/public/v1/tickers?exchange=KuCoin&pair=ATOM-USDT

**Comment by Tkd-Alex** [comment]
This is what i see
`{"message":"This API is deprecated and will be disabled by Oct 31, to use the new version please go to https://openapi.coinstats.app ."}`

**Comment by freQniK** [comment]
Fixed in https://github.com/MathNodes/meile-gui/commit/7177466f21d0676c97b7515e298c7f4daeeb9f44
