### ISSUE TITLE
[BUG] Unsubscribe bug may cause unsubscribe function to not work on Linux

### ISSUE THREAD

**Issue by freQniK** [MathNodes/meile-gui#63]
![Screenshot_2023-12-01_23-17-05](https://github.com/MathNodes/meile-gui/assets/93114223/e3d3c950-0093-4d95-ada2-a35239c5a670)

I got this on Ubuntu 20.04 running v1.7.14. I tested the same code on another Ubunut 20.04 v1.7.14 and I was able to unsubscribe. Not sure where the disconnect is.  I think this is related to the privkey retrieved from the key-ring dir but not I'm sure. Somewhere related to this stretch of code in [src/cli/wallet.py](https://github.com/MathNodes/meile-gui/blob/232fc5ecb9e1f270dc16016f1d32f0aa073204db/src/cli/wallet.py#L250)

```python
        wallet = LocalWallet(PrivateKey(priv_key_bytes), prefix="sent")
        address = wallet.address()

        print(f"Address: {address},\nSubscription ID: {subId}")
 
        try: 
            tx = Transaction()
            tx.add_message(MsgCancelRequest(frm=str(address), id=int(subId)))
    
            tx = prepare_and_broadcast_basic_transaction(client, tx, wallet)
            tx.wait_to_complete()
            
```
Posting this in case other people notice a similar message.

**Comment by MathNodes** [comment]
This was only an error on my one HP box. Strange things on that box. Closing for now.
