### ISSUE TITLE
Add NodeScreen Overlay

### ISSUE THREAD

**Issue by MathNodes** [MathNodes/meile-gui#65]
When clicking on a country in the left column of the MainScreen, the NodeScreen will overlay the map with available node cards. These node cards can also be dropdown boxes that display more information about the node, such as User Submitted Ratings, Node Formula, Health Check Verified, Get Details (Remote Query to see real-time data of the node) etc. 

This new NodeScreen overlay should have icons to go back to the Map (i.e., destroy NodeScreen)

![Image](https://github.com/MathNodes/meile-gui/assets/102208536/94e7c8d7-ba6b-4315-9d03-0db0f7acebc8)

**Comment by Tkd-Alex** [comment]
![image](https://github.com/MathNodes/meile-gui/assets/14061593/8239ed50-d89c-4102-8550-fbbd997fd8c9)

maybe It's more clear without data table

**Comment by Tkd-Alex** [comment]
![image](https://github.com/MathNodes/meile-gui/assets/14061593/e3bb9f6c-e069-4d55-aee1-1801f8016fd0)

**Comment by MathNodes** [comment]
This is completed and working as planned.
