### ISSUE TITLE
Create a "Featured Nodes" within select countries

### ISSUE THREAD

**Issue by MathNodes** [MathNodes/meile-gui#7]
Goal is to allow dVPN Node operators to pay a small monthly fee (~1,000 dvpn/mo @ current rates) to have their nodes listed at the top of select countries with a "promoted" or akin badge in the listing. 

Current select countries and # of feature nodes stands at:
* Canada - 8
* USA - 20
* Singapore - 4
* Finland - 17
* Germany - 20
* Netherlands - 7
* Norway - 3
* Polad - 2
* United Kingdom - 5
* Australia - 5

There will be a form on [mathnodes.com](https://mathnodes.com) that node operators can fill out and send the dvpn to a wallet address. Our server will verify payment and include the node's address (sentnode...) in a MySQL database that Meile will pull from when loading the nodes under these select countries.

**Comment by freQniK** [comment]
This will be deprecated as soon as we have "preferred" subscription plans.
