### ISSUE TITLE
Add Fields to Settings Screen

### ISSUE THREAD

**Issue by MathNodes** [MathNodes/meile-gui#70]
In the settings I would like two more options for users to select in case certain servers are blocked in their region:

* `gRPC` dropdown of available MathNodes gRPC servers and known public ones
* `MN-API` dropdown of future MathNodes Aimo Koivunen API servers (as soon as we install more infrastructure)

**Comment by MathNodes** [comment]
Once settings are saved... settings should persist through rest of the app and not require a restart like current selection of RPC. This can be achieved by writing to config.ini and reading from it before making requests to these servers

**Comment by Tkd-Alex** [comment]
Not the best graphically, but It's work! 😄 

![Image](https://github.com/MathNodes/meile-gui/assets/14061593/8ea151b9-ea29-4360-817f-4b6bdf2acf9b)

https://github.com/Tkd-Alex/meile-gui/commit/9087dc8a15278e4cff7156539b3c08715ea82735

**Comment by MathNodes** [comment]
This won't do. The fields need to be organized one after the other. This is why I used FloatLayout - more control on where they end up.

Also add "API" with "https://api.sentinel.mathnodes.com" and any other ones from the chain registry.

Also add "MN-API" with entry "https://aimokoivunen.mathnodes.com:5000"

You may create a list in konstants of "MN-API" with this entry. We will be expanding our mathnodes api to more servers. 

You may also create a list in konstants "APIs" with the chain registry public APIs.

⁣freQniK- Core Developer
MathNodes
www.mathnodes.com​

**Comment by Tkd-Alex** [comment]
Ok about, API, APISs and MN-API.
About the layout I've pushed another commit with GridLayout, instead of MDFloatLayout

https://github.com/Tkd-Alex/meile-gui/commit/67e0e251f17a87cdef550fcac9fbe592471c7270

With the Grid probably you don't have enought control but It's sure that the items are where they belong 🤣 

![image](https://github.com/MathNodes/meile-gui/assets/14061593/3a91f67e-fbf4-44c3-a3a0-20439a074bb7)

**Comment by Tkd-Alex** [comment]
Here an update, I have only some issues with the layout :disappointed: 
![image](https://github.com/MathNodes/meile-gui/assets/14061593/6db45b59-b1b3-413b-bc06-ada67c17d170)

96b6fabdd5932265b063eb8d370d1c9dff7b886a
