### ISSUE TITLE
Change Resolution to 16:9

### ISSUE THREAD

**Issue by freQniK** [MathNodes/meile-gui#75]
Windows is already a 16:9 ratio... just need to to change linux and OS X

Resolution change is in the following:

https://github.com/MathNodes/meile-gui/blob/c2fecdd76d7755ceef07003c8a65e3ff3b1d8d38/src/main/main.py#L26

and

https://github.com/MathNodes/meile-gui/blob/c2fecdd76d7755ceef07003c8a65e3ff3b1d8d38/src/main/main.py#L43
https://github.com/MathNodes/meile-gui/blob/c2fecdd76d7755ceef07003c8a65e3ff3b1d8d38/src/main/main.py#L44

**Comment by MathNodes** [comment]
16:10
