### ISSUE TITLE
Migrate from sentinel-cli to sentinel_sdk

### ISSUE THREAD

**Issue by MathNodes** [MathNodes/meile-gui#82]
Now the Python SDK is completed. The next 2.x release will include this instead of relying on pexpect/wexpect and sentinel-cli. This will simplify code and make it more portable and easier to compile binaries for Windows.

**Comment by Tkd-Alex** [comment]
In order to start this migration we had to wait for the official package of mospy with the get_tx method implementation

**Comment by Tkd-Alex** [comment]
this issue is in conflict with the #83 , or you would to replace sentinel-cli with sdk only for transaction like Subcribiption / Start/End Session and relay the queries over the meile-cache-server?

**Comment by MathNodes** [comment]
So to load the Node dara would just query the meile-cache-server for the same information that sentinel-cli currently produces. All other "wallet" operations would be handled by the SDK

**Comment by MathNodes** [comment]
@Tkd-Alex Going thru your commits. Amazing!

**Comment by MathNodes** [comment]
One thing I would add before `SubscribeToNode` in https://github.com/Tkd-Alex/meile-gui/commit/442b37a51e66d926226bf8acd8c0d515fa609db1 is to add a check of the wallet balance versus the amount to deposit. If the balance is lower than the deposit amount an Exception should be raised. I'm unsure what the blockchain message would be if we attempt to subscribe with insufficient balance, nevertheless a check beforehand would solve the troubleshooting of the blockchain message.

**Comment by MathNodes** [comment]
Actually a "insufficient" funds would be the in the raw_log of the tx response as I check for this in `ParseSubscribe` that is now deprecated in https://github.com/Tkd-Alex/meile-gui/commit/e6ebb84f5f2c937eef1c2570715bdb060d206405 . But adding the check before broadcasting I think is a better solution

**Comment by MathNodes** [comment]
Finally got through it all. Everything looks good. Please review the few remarks I made. Thank you so much!

**Comment by Tkd-Alex** [comment]
- Check wallet balance before continue to subscribe: https://github.com/Tkd-Alex/meile-gui/commit/3e5e3b15d21e5d1c7666b9a3b4f9564978cc0dc1
- Move v2ray configuration dataclass from konstants to v2ray dedicated file: https://github.com/Tkd-Alex/meile-gui/commit/d653193c15d695f33d86d9717c117304b17df85f

**Comment by MathNodes** [comment]
Looks good. Thank you!

⁣freQniK- Core Developer
MathNodes
www.mathnodes.com​

**Comment by MathNodes** [comment]
Keeping this open for now. Although the code looks stellar it is untested in Meile currently. Will provide update if need be...
