### ISSUE TITLE
Check for Allowed Characters in Wallet Name

### ISSUE THREAD

**Issue by MathNodes** [MathNodes/meile-gui#85]
A user had an error this week and it was the first I saw. His wallet name contained a quote `'` which confused the sentinel-cli. This error will be addressd when we are fully migrated to the SDK. But there should be a check to not allow certain characters in the Wallet NAME:

![Image](https://github.com/MathNodes/meile-gui/assets/102208536/c03e1e7c-e987-4e02-8ec9-8427bfa98775)

**Comment by MathNodes** [comment]
@Tkd-Alex if you could create a check for special characters in 
https://github.com/MathNodes/meile-gui/blob/b9ae699f56f673bc83bd2cf835c7bc48c915f74f/src/ui/screens.py#L75

such as ()'"[] etc and create a little label with opacity 0 setting opacity to 1 warning user that special characters are not allowed in wallet_name

spaces are okay.

**Comment by Tkd-Alex** [comment]
![image](https://github.com/MathNodes/meile-gui/assets/14061593/004cc767-1ccc-4363-8b8e-aae9cc31b5c6)
